version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
  spring-app:
    image: ${IMAGE_NAMEb}
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8082"

  angular-app:
    image: ${IMAGE_NAMEf}
    ports:
      - "4200:80"
    depends_on:
      - spring-app